window.VIDEO_FIELD_CASES = {
    aquariumVideo: {title:'🐠 Aquarium / Bể Cá', html:`
      <div class="field-case-hero"><div class="field-case-hero-title">🎯 V-AQUARIUM — Base Video Preset</div><div class="field-case-hero-sub">Dùng làm preset mặc định, sau đó chỉ đổi 1–2 thông số theo shot.</div></div>
      <div class="quick-settings-card"><div class="settings-grid">
        <div class="setting-item"><div class="setting-label">RECORD</div><div class="setting-value">XAVC S HD · 25p · 50M</div></div>
        <div class="setting-item"><div class="setting-label">SHUTTER</div><div class="setting-value">1/50 s</div></div>
        <div class="setting-item"><div class="setting-label">APERTURE</div><div class="setting-value">F2.8–4</div></div>
        <div class="setting-item"><div class="setting-label">ISO</div><div class="setting-value">AUTO / ~800–3200*</div></div>
        <div class="setting-item"><div class="setting-label">FOCUS</div><div class="setting-value">AF-C / AF-S / MF</div></div>
        <div class="setting-item"><div class="setting-label">WB / PP</div><div class="setting-value">AWB / PP OFF</div></div>
      </div></div>
      <div class="section-card"><div class="section-card-title">🏠 1. Toàn bộ bể</div><div class="field-case-setup">25p → 1/50 → F4 → ISO theo ánh sáng → AF-S/MF → AWB</div><div class="step-desc"><b>Mục tiêu:</b> lấy đủ bố cục bể, cá, cây và ánh sáng. Đặt máy cố định 5–10 giây hoặc lia rất chậm. Vì 50mm trên APS-C ≈ 75mm equivalent, hãy lùi đủ xa để lấy được toàn bể.</div></div>
      <div class="section-card"><div class="section-card-title">🐟 2. Cá đang bơi</div><div class="field-case-setup">25p → 1/50 → F2.8–4 → ISO theo ánh sáng → AF-C</div><div class="step-desc"><b>AF-C</b> khi cá di chuyển. Nếu cá thường xuyên đi qua cây/kính khiến AF nhảy chủ thể, chuyển <b>MF</b> và khóa focus tại vùng cá hay bơi. Muốn slow motion 2× trên timeline 25p: <b>50p → 1/100</b>.</div></div>
      <div class="section-card"><div class="section-card-title">🌿 3. Cây / đá / bong bóng / chi tiết</div><div class="field-case-setup">25p → 1/50 → F1.8–2.8 → ISO theo ánh sáng → MF/AF-S</div><div class="step-desc"><b>F1.8–2.8</b> tạo background blur đẹp. Với shot cố định, MF thường dễ kiểm soát hơn AF. Quay mỗi detail khoảng 5–10 giây để có đủ footage dựng.</div></div>
      <div class="section-card"><div class="section-card-title">🌙 4. Cá sáng — nền tối</div><div class="field-case-setup">25p → 1/50 → F1.8–2.8 → ISO bắt đầu ~800–1600 → PP OFF</div><div class="step-desc">Giảm/tắt đèn phòng để đèn bể trở thành nguồn sáng chính. Không cần cố làm sáng background; để phần tối tạo tương phản cho cá và cây.</div></div>
      <div class="section-card"><div class="section-card-title">🪟 5. Xử lý reflection trên kính</div><div class="field-case-setup">Đèn phòng ↓ → lens gần kính → đổi góc → lau kính</div><div class="step-desc">Reflection là vấn đề về <b>vị trí + ánh sáng</b> trước khi là exposure. Tắt nguồn sáng phía sau camera, đưa lens gần kính nhưng không chạm kính, xoay nhẹ góc máy và lau kính sạch.</div></div>
      <div class="section-card"><div class="section-card-title">🎬 6. Chuyển động máy</div><div class="field-case-setup">Locked → slow pan → slow push-in → gentle follow</div><div class="step-desc">Ưu tiên chuyển động nhỏ và chậm. Không lia nhanh vì góc nhìn 75mm equivalent khá hẹp. Nếu chưa chắc, <b>locked shot</b> thường đẹp và dễ dựng hơn.</div></div>
      <div class="section-card"><div class="section-card-title">🎙 7. Audio</div><div class="field-case-setup">Built-in stereo mic / compatible external mic via Multi Interface Shoe</div><div class="step-desc">Tiếng bơm/filter có thể thành noise nền. Nếu muốn video chill sạch hơn, quay thêm một đoạn ambience riêng để dùng khi dựng. A6000 không có jack mic 3.5mm thông thường.</div></div>
      <div class="section-card"><div class="section-card-title">🎞 8. Sequence 5 shot</div><div class="field-case-setup">1. Whole tank → 2. Fish through plants → 3. Plant/bubble detail → 4. Fish on dark BG → 5. Slow pan</div><div class="step-desc">Mỗi shot 5–10 giây. Khi dựng: <b>Wide → Medium → Close-up → Detail → Wide</b>.</div></div>
      <div class="section-card"><div class="section-card-title">⚡ Quick Cheat Sheet</div><div class="field-case-setup">General: 25p/1⁄50/F2.8–4 · Fish: 25p/1⁄50/F2.8–4/AF-C · Slow-mo: 50p/1⁄100 · Detail: F1.8–2.8/MF · Dark BG: F1.8–2.8/ISO ~800–1600</div></div>
      <div class="field-case-callout"><b>⭐ Nếu chỉ nhớ một công thức:</b> 25p · 1/50 · F2.8–4 · ISO Auto · AF-C → sau đó chỉ đổi focus/khẩu/ISO theo từng shot.</div>
    </div>`,},

    morningRoad:{title:'🌅 Morning Warm Sun — Cinematic Road',html:`
      <div class="field-case-hero"><div class="field-case-hero-title">🎯 V-MORNING ROAD — Base Video Preset</div><div class="field-case-hero-sub">Cho cảnh buổi sáng nắng ấm có đường + hai hàng cây + bầu trời. 50mm trên APS-C ≈ 75mm equivalent, nên ưu tiên bố cục gọn và chuyển động chậm.</div></div>
      <div class="quick-settings-card"><div class="settings-grid">
        <div class="setting-item"><div class="setting-label">RECORD</div><div class="setting-value">XAVC S HD · 25p · 50M</div></div>
        <div class="setting-item"><div class="setting-label">SHUTTER</div><div class="setting-value">1/50 s</div></div>
        <div class="setting-item"><div class="setting-label">APERTURE</div><div class="setting-value">F4–5.6</div></div>
        <div class="setting-item"><div class="setting-label">ISO</div><div class="setting-value">AUTO · low first</div></div>
        <div class="setting-item"><div class="setting-label">FOCUS</div><div class="setting-value">AF-S / MF static · AF-C people</div></div>
        <div class="setting-item"><div class="setting-label">WB / PP</div><div class="setting-value">Lock WB · PP OFF</div></div>
      </div></div>
      <div class="section-card"><div class="section-card-title">🛣 1. Establishing — đường + cây + trời</div><div class="field-case-setup">25p → 1/50 → F5.6 → ISO theo ánh sáng → AF-S/MF → WB lock</div><div class="step-desc">Đặt máy cố định 5–10 giây hoặc push-in rất nhẹ. Vì góc nhìn 75mm equivalent khá hẹp, đừng cố làm shot quá rộng; chọn đoạn đường đẹp nhất.</div></div>
      <div class="section-card"><div class="section-card-title">🌳 2. Tree framing</div><div class="field-case-setup">25p → 1/50 → F4–5.6 → MF/AF-S → slow pan</div><div class="step-desc">Lia rất chậm từ một bên hàng cây xuống điểm hội tụ của con đường. Chỉ lia trong phạm vi nhỏ; 50mm handheld dễ lộ rung.</div></div>
      <div class="section-card"><div class="section-card-title">☀️ 3. Sun through leaves</div><div class="field-case-setup">25p → 1/50 → F4 → ISO thấp nhất phù hợp → WB lock → ND nếu quá sáng</div><div class="step-desc">Giữ highlight của nắng và lá. Nếu muốn giữ 1/50 mà ánh sáng quá mạnh, dùng ND thay vì đẩy shutter rất cao. Có thể cho flare nhẹ nếu hợp style.</div></div>
      <div class="section-card"><div class="section-card-title">🚶 4. Walker in the frame</div><div class="field-case-setup">25p → 1/50 → F4 → AF-C → Zone/Wide → WB lock</div><div class="step-desc">Giữ máy đơn giản và để người tạo movement. Không đổi sang 1/500 chỉ vì người đang đi nếu bạn muốn motion tự nhiên.</div></div>
      <div class="section-card"><div class="section-card-title">🎞 5. 6-shot sequence</div><div class="field-case-setup">1. Road → 2. Tree tunnel → 3. Sun through leaves → 4. Road detail → 5. Walker → 6. End wide</div><div class="step-desc">Mỗi shot khoảng 5–10 giây. Dựng từ wide → medium → detail → human scale rồi kết bằng một shot rộng vừa đủ.</div></div>
      <div class="section-card"><div class="section-card-title">🎙 6. Sound</div><div class="field-case-setup">Record clean ambience · avoid wind/handling noise</div><div class="step-desc">Buổi sáng đường phố có ambience tốt. Quay thêm 10–20 giây ambience riêng nếu muốn dựng mượt giữa các shot.</div></div>
      <div class="field-case-callout"><b>⭐ Nếu chỉ nhớ một công thức:</b> 25p · 1/50 · F4–5.6 · ISO Auto · WB lock → giữ máy đơn giản, để ánh sáng và đường dẫn kể câu chuyện.</div>
    </div>`},
    sunCanopy:{title:'☀️ Sun Through Canopy — Slow Pan',html:`
      <div class="field-case-hero"><div class="field-case-hero-title">🎯 V-SUN CANOPY — Slow Pan</div><div class="field-case-hero-sub">Một shot rất đơn giản nhưng dễ đẹp: lá + cành + nắng xiên + bầu trời sáng.</div></div>
      <div class="quick-settings-card"><div class="settings-grid"><div class="setting-item"><div class="setting-label">RECORD</div><div class="setting-value">25p · 50M</div></div><div class="setting-item"><div class="setting-label">SHUTTER</div><div class="setting-value">1/50 s</div></div><div class="setting-item"><div class="setting-label">APERTURE</div><div class="setting-value">F4</div></div><div class="setting-item"><div class="setting-label">ISO</div><div class="setting-value">AUTO / low</div></div><div class="setting-item"><div class="setting-label">FOCUS</div><div class="setting-value">AF-S / MF</div></div><div class="setting-item"><div class="setting-label">WB</div><div class="setting-value">LOCK</div></div></div></div>
      <div class="section-card"><div class="section-card-title">🌳 Shot 1 — từ lá sang trời</div><div class="field-case-setup">Start on dark leaves → slow pan → reveal bright sky</div><div class="step-desc">Đừng lia nhanh. Khoảng 5–8 giây là đủ cho một shot dùng được.</div></div>
      <div class="section-card"><div class="section-card-title">☀️ Shot 2 — flare nhẹ</div><div class="field-case-setup">Sun near frame edge → keep 1/50 → ND if needed</div><div class="step-desc">Cho mặt trời chạm mép khung để có flare nhẹ. Nếu highlight quá mạnh, đổi góc trước khi đổi setting.</div></div>
      <div class="section-card"><div class="section-card-title">🎯 Focus</div><div class="field-case-setup">Static branch → AF-S/MF</div><div class="step-desc">Nếu AF hunting giữa lá và trời, chuyển MF hoặc chọn một vùng có texture rõ.</div></div>
    </div>`},
    morningWalker:{title:'🚶 Morning Walker — Human Scale B-roll',html:`
      <div class="field-case-hero"><div class="field-case-hero-title">🎯 V-WALKER — Let the Subject Create Movement</div><div class="field-case-hero-sub">Giữ camera đơn giản, để người đi bộ/xe đạp tạo chuyển động trong khung cảnh lớn.</div></div>
      <div class="quick-settings-card"><div class="settings-grid"><div class="setting-item"><div class="setting-label">RECORD</div><div class="setting-value">25p · 50M</div></div><div class="setting-item"><div class="setting-label">SHUTTER</div><div class="setting-value">1/50 s</div></div><div class="setting-item"><div class="setting-label">APERTURE</div><div class="setting-value">F4–5.6</div></div><div class="setting-item"><div class="setting-label">ISO</div><div class="setting-value">AUTO</div></div><div class="setting-item"><div class="setting-label">FOCUS</div><div class="setting-value">AF-C · Zone/Wide</div></div><div class="setting-item"><div class="setting-label">WB</div><div class="setting-value">LOCK</div></div></div></div>
      <div class="section-card"><div class="section-card-title">🚶 Static camera</div><div class="field-case-setup">Camera locked → subject crosses frame → 5–10 s</div><div class="step-desc">Đây là shot dễ nhất và rất hợp với 50mm. Chọn trước vùng đẹp trên đường rồi chờ người đi vào.</div></div>
      <div class="section-card"><div class="section-card-title">🏃 Gentle follow</div><div class="field-case-setup">25p → 1/50 → AF-C → move very slowly</div><div class="step-desc">Chỉ follow khi có đủ khoảng trống để bước ổn định. Vì 50mm ≈ 75mm equivalent, rung sẽ lộ rõ hơn lens wide.</div></div>
      <div class="section-card"><div class="section-card-title">🌤 Exposure</div><div class="field-case-setup">Keep 1/50 → adjust aperture/ISO → ND when bright</div><div class="step-desc">Nếu ngoài trời nắng mạnh và muốn giữ 1/50, dùng ND filter thay vì tăng shutter quá cao.</div></div>
    </div>`},
    cafe:{title:'☕ Cafe Cinematic B-roll',html:'<p><b>V1/V3:</b> 25p · 1/50 · F2.8 · ISO Auto. Use static shots or a slow push-in. Coffee/decor: AF-S or MF; use AF-C only when the subject moves.</p>'},
    night:{title:'🌙 Night — Lit Subject / Dark Background',html:'<p><b>V3:</b> 25p · 1/50 · F1.8–2 · ISO Auto. Use street/shop light as the key light and keep the background dark. Do not brighten the whole frame just to reveal the sky.</p>'},
    overcast:{title:'☁️ Overcast Outdoor B-roll',html:'<p><b>V1:</b> 25p · 1/50 · F2.8–4 · ISO Auto. Good for people, greenery and soft portraits. Lock WB for a connected sequence.</p>'},
    rain:{title:'🌧 Rain / Reflection',html:'<p><b>V3:</b> 25p · 1/50 · F1.8–2.8. Look for umbrellas, wet roads, reflections and rain through glass. Protect the A6000 + 50mm because the system is not weather-sealed.</p>'},
    talking:{title:'👤 Talking Head',html:'<p><b>V5:</b> 25p · 1/50 · F2–2.8 · AF-C · Face Detection where appropriate. Prioritize good light and clean audio. 50mm requires enough working distance.</p>'},
    walking:{title:'🚶 Person Walking Through Frame',html:'<p><b>V6:</b> 25p · 1/50 · F2.8–4 · AF-C. Keep the camera mostly static and let the person create the movement. Do not jump to 1/500 just because the subject moves if you want natural cinematic motion.</p>'}
  };
